# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jani/GitHub-repos/RasekoSyksy22/hirviporukka/sankeyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sankeyDialog(object):
    def setupUi(self, sankeyDialog):
        sankeyDialog.setObjectName("sankeyDialog")
        sankeyDialog.resize(627, 609)

        self.retranslateUi(sankeyDialog)
        QtCore.QMetaObject.connectSlotsByName(sankeyDialog)

    def retranslateUi(self, sankeyDialog):
        _translate = QtCore.QCoreApplication.translate
        sankeyDialog.setWindowTitle(_translate("sankeyDialog", "Sankey-kaavio"))
